<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<gradle-project-properties>
  <!--DO NOT EDIT THIS FILE! - Used by the Gradle plugin of NetBeans.-->
  <source-level>1.8</source-level>
</gradle-project-properties>
